config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  
  get 'about' , to: 'pages#about'

  get 'careers' , to: 'pages#careers'

  get 'client-stories', to: 'pages#client_stories'

  get '/support/faq' , to: 'pages#faq'

  get 'invoice-factoring' , to: 'pages#invoice_factoring'

  get 'line-of-credit' , to: 'pages#line_of_credit'

  get 'partner' , to: 'pages#partner'

  get 'press' , to: 'pages#press'

  get '/terms/privacy-policy' , to: 'pages#privacy'

  get 'support' , to: 'pages#support'

  get 'terms' , to: 'pages#terms'

  devise_for :users,
             path: '',
             path_names: {sign_in: 'login', sign_out: 'logout', edit: 'edit', sign_up: 'register'},
             controllers: {registrations: 'registrations'}
  
  resources :companies, except: [:edit] do
    member do
      get 'funding'
      get 'info'
      get 'photo_upload'
      get 'contact'
      get 'edit'
    end
  end
  
  get 'dashboard' => 'dashboards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  
  validates :amount, presence: true
  validates :financing_type, presence: true
  validates :financing_time, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  validates :first_name, presence: true, length: {maximum: 25}
  validates :last_name, presence: true, length: {maximum: 25}
  
  has_many :companies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  
  def after_sign_in_path_for(resource_or_scope)
    dashboard_path
  end
  
  def configure_permitted_parameters
    added_attrs = [:email, :password, :password_confirmation, :first_name, :last_name, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, except: [:index, :new, :create]
  before_action :authenticate_user!
  
  def index
    @companies = Company.all
  end

  def new
    @company = current_user.companies.build
  end

  def create
    @company = current_user.companies.build(company_params)
    
    if @company.save
      redirect_to funding_company_path(@company), notice: "Your company was created successfully! We will be in touch soon!"
    else
      flash[:alert] = "Oops, something went wrong."
      render :new
    end
  end
  
  def show
  end

  def funding
  end

  def info
  end

  def photo_upload
  end

  def contact
  end

  def update
    if @company.update(company_params)
      flash[:notice] = "Your changes were saved."
    else
      flash[:alert] = "Oops, something went wrong."
    end
    redirect_back(fallback_location: request.referer)
  end
  
  private
  
    def set_company
      @company = Company.find(params[:id])
    end
  
    def company_params
      params.require(:company).permit(:amount, :financing_type, :financing_time, :company_name, :company_phone, :trade_name, :company_address, :company_suite, :company_city, :company_state, :company_zip, :tax_id, :entity_type, :annual_revenue, :sell_to)
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def index
    @companies = current_user.companies
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def careers
  end

  def client_stories
  end

  def faq
  end

  def home
  end

  def invoice_factoring
  end

  def line_of_credit
  end

  def partner
  end

  def press
  end

  def privacy
  end

  def support
  end

  def terms
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
    def update_resource(resource, params)
    # Require current password if user is trying to change password.
    return super if params["password"]&.present?

    # Allows user to update registration information without password.
    resource.update_without_password(params.except("current_password"))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(key)
    case key
    when "notice" then "alert alert-info"
    when "alert" then "alert alert-danger"
    end
  end
      
  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "https://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
 def devise_error_messages!
  return '' if resource.errors.empty?

   messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
   sentence = I18n.t('errors.messages.not_saved',
   count: resource.errors.count,
   resource: resource.class.model_name.human.downcase)

   html = <<-HTML
   <div class="alert devise"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    #{messages}
   </div>
   HTML

   html.html_safe
 end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/companies/_company_menu.html.erb
<section id="sidebar">
  <nav>
    <% if current_page?(funding_company_path) %>
      <li><%= link_to "Funding", funding_company_path, class: "sidebar-link active" %>
      </li>
    <% else %>
    <li><%= link_to "Funding", funding_company_path, class: "sidebar-link" %></li>
    <% end %>
    
    <% if current_page?(info_company_path) %>
    <li><%= link_to "Company Info", info_company_path, class: "sidebar-link active" %></li>
    <% else %>
    <li><%= link_to "Company Info", info_company_path, class: "sidebar-link" %></li>
    <% end %>
    
    <% if current_page?(contact_company_path) %>
    <li><%= link_to "Contact Info", contact_company_path, class: "sidebar-link active" %></li>
    <% else %>
    <li><%= link_to "Contact Info", contact_company_path, class: "sidebar-link" %></li>
    <% end %>
    
  </nav>  
</section>
  

app/views/companies/contact.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-3">
      <%= render 'company_menu' %>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">Contact Info</div>
        <div class="panel-body">
          <div class="container">
            <%= form_for @company do |f| %>
             
              <div class="row">
                <div class="col-lg-4">
                  <div class="form-group">
                    <label>Company Address</label>
                    <%= f.text_field :company_address, placeholder: "Address", class: "form-control", required: true %>
                  </div>
                </div>
                <div class="col-lg-4">
                  <div class="form-group">
                    <label>Apt or Suite</label>
                    <%= f.text_field :company_suite, placeholder: "Apt or Suite", class: "form-control", required: true %>
                  </div>
                </div>
                <div class="col-lg-4">
                  <div class="form-group">
                    <label>City</label>
                    <%= f.text_field :company_city, placeholder: "City", class: "form-control", required: true %>
                  </div>
                </div>
              </div>
              
              <div class="row">
                <div class="col-lg-4">
                  <div class="form-group">
                    <label>State</label>
                    <%= f.text_field :company_state, placeholder: "State", class: "form-control", required: true %>
                  </div>
                </div>
                <div class="col-lg-4">
                  <div class="form-group">
                    <label>Zip Code</label>
                    <%= f.text_field :company_zip, placeholder: "Zip", class: "form-control", required: true %>
                  </div>
                </div>
                <div class="col-lg-4">
                  <div class="form-group">
                    <label>Phone Number</label>
                    <%= f.text_field :company_phone, placeholder: "Phone Number", class: "form-control", required: true %>
                  </div>
                </div>
              </div>
              
              <%= f.submit "Save", class: "btn btn-primary" %>
              
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/companies/create.html.erb
<h1>Company#create</h1>
<p>Find me in app/views/company/create.html.erb</p>

app/views/companies/funding.html.erb
<div class="container content">
  <div class="alert alert-warning alert-dismissible d-none d-lg-block" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <span class="alert-link"></span><strong>Hi, <%= current_user.first_name %>!</strong> Use the navigation links to tell us a little more about your company.
  </div>
  <br>
  <div class="row">
    <div class="col-md-3">
      <%= render 'company_menu' %>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">Funding</div>
        <div class="panel-body">
          <div class="container">
            <%= form_for @company do |f| %>
        
              <div class="row">
                <div class="col-lg-4 select">
                  <div class="form-group">
                    <label>How much do you need?</label>
                    <%= f.select :amount, [["$5000 - $10,000", "$5000 - $10,000"], ["$10,001 - $15,000", "$10,001 - $15,000"], ["$15,001 - $20,000", "$15,001 - $20,000"], ["$20,001 - $25,000", "$20,001 - $25,000"], ["$25,001 - $30,000", "$25,001 - $30,000"], ["$30,001 - $35,000", "$30,001 - $35,000"], ["$35,001 - $50,000", "$35,001 - $50,000"], ["$50,001 - $75,000", "$50,001 - $75,000"], ["$75,001 - $150,000", "$75,001 - $150,000"], ["$150,001 - $250,000", "$150,001 - $250,000"], ["More than $250,000", "More than $250,000"]],
                                  id: "amount", prompt: "Select...", class: "form-control" %>
                  </div>
                </div>
                <div class="col-lg-4 select">
                  <div class="form-group">
                    <label>Which Type of financing?</label>
                    <%= f.select :financing_type, [["Invoice Factoring (up to $5,000,000)", "Invoice Factoring (up to $5,000,000)"], ["Line of credit (up to $250,000)", "Line of credit (up to $250,000)"], ["Not sure", "Not sure"]],
                                  id: "financing_type", prompt: "Select...", class: "form-control" %>
                  </div>
                </div>
                <div class="col-lg-4 select">
                  <div class="form-group">
                    <label>How fast do you need the funds?</label>
                    <%= f.select :financing_time, [["Within 1 week", "Within 1 week"], ["Within 1 month", "Within 1 month"], ["More than a month", "More than a month"]],
                                  id: "financing_time", prompt: "Select...", class: "form-control" %>
                  </div>
                </div>
              </div>

              <%= f.submit "Save", class: "btn btn-primary" %>

              <br>

            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/companies/index.html.erb
<div class="container content">
  <h3><strong>Companies</strong></h3>
  <br>
  
  <div class="panel panel-default">
    <div class="media-body">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Amount</th>
            <th>Financing Type</th>
            <th>Financing Time</th>
            <th>Annual Revenue</th>
            <th>Phone</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @companies.each do |company| %>
            <tr>
              <td><%= company.company_name %></td>
              <td><%= company.amount %></td>
              <td><%= company.financing_type %></td>
              <td><%= company.financing_time %></td>
              <td><%= company.annual_revenue %></td>
              <td><%= company.company_phone %></td>
              <td><%= link_to 'Show', company %></td>
              <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>  
    </div>
  </div>
</div>

app/views/companies/info.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-3">
      <%= render 'company_menu' %>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">Company Info</div>
        <div class="panel-body">
          <div class="container">
            <%= form_for @company do |f| %>
             
              <div class="row">
                <div class="col-lg-4">
                  <div class="form-group">
                    <label>Company Name</label>
                    <%= f.text_field :company_name, placeholder: "Legal Company Name", class: "form-control", required: true %>
                  </div>
                </div>
                <div class="col-lg-4">
                  <div class="form-group">
                    <label>Trade Name</label>
                    <%= f.text_field :trade_name, placeholder: "Optional", class: "form-control" %>
                  </div>
                </div>
                <div class="col-lg-4">
                  <div class="form-group">
                    <label>Tax ID/EIN or SSN</label>
                    <%= f.text_field :tax_id, placeholder: "1234567", class: "form-control", required: true %>
                  </div>
                </div>
              </div>
              
              <div class="row">
                <div class="col-lg-4 select">
                  <div class="form-group">
                    <label>Entity Type</label>
                    <%= f.select :entity_type, [["Within 1 week", "Within 1 week"], ["Within 1 month", "Within 1 month"], ["More than a month", "More than a month"]], required: true,
                                  id: "entity_type", prompt: "Select...", class: "form-control" %>
                  </div>
                </div>
                <div class="col-lg-4 select">
                  <div class="form-group">
                    <label>Annual Revenue</label>
                    <%= f.select :annual_revenue, [["Within 1 week", "Within 1 week"], ["Within 1 month", "Within 1 month"], ["More than a month", "More than a month"]], required: true,
                                  id: "annual_revenue", prompt: "Select...", class: "form-control" %>
                  </div>
                </div>
                <div class="col-lg-4 select">
                  <div class="form-group">
                    <label>Who are your Customers?</label>
                    <%= f.select :sell_to, [["Within 1 week", "Within 1 week"], ["Within 1 month", "Within 1 month"], ["More than a month", "More than a month"]], required: true,
                                  id: "sell_to", prompt: "Select...", class: "form-control" %>
                  </div>
                </div>
              </div>
              
              <%= f.submit "Save", class: "btn btn-primary" %>
              
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/companies/new.html.erb
<div class="container content">
  <div class="panel panel-default">
    <div class="panel-heading">Funding</div>
    <div class="panel-body">
      <div class="container">
       
        <%= form_for @company do |f| %>
        
        <div class="row">
          <div class="col-md-4 select">
            <div class="form-group">
              <label>How much do you need?</label>
              <%= f.select :amount, [["$5000 - $10,000", "$5000 - $10,000"], ["$10,001 - $15,000", "$10,001 - $15,000"], ["$15,001 - $20,000", "$15,001 - $20,000"], ["$20,001 - $25,000", "$20,001 - $25,000"], ["$25,001 - $30,000", "$25,001 - $30,000"], ["$30,001 - $35,000", "$30,001 - $35,000"], ["$35,001 - $50,000", "$35,001 - $50,000"], ["$50,001 - $75,000", "$50,001 - $75,000"], ["$75,001 - $150,000", "$75,001 - $150,000"], ["$150,001 - $250,000", "$150,001 - $250,000"], ["More than $250,000", "More than $250,000"]],
                                  id: "amount", prompt: "Select...", class: "form-control" %>
            </div>
          </div>
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Which Type of financing?</label>
              <%= f.select :financing_type, [["Invoice Factoring (up to $5,000,000)", "Invoice Factoring (up to $5,000,000)"], ["Line of credit (up to $250,000)", "Line of credit (up to $250,000)"], ["Not sure", "Not sure"]],
                                  id: "financing_type", prompt: "Select...", class: "form-control" %>
            </div>
          </div>
          <div class="col-md-4 select">
            <div class="form-group">
              <label>How fast do you need the funds?</label>
              <%= f.select :financing_time, [["Within 1 week", "Within 1 week"], ["Within 1 month", "Within 1 month"], ["More than a month", "More than a month"]],
                                  id: "financing_time", prompt: "Select...", class: "form-control" %>
            </div>
          </div>
        </div>
                
        <%= f.submit "Create Your Company", class: "btn btn-primary" %>
        
        <br>
        
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/companies/photo_upload.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-3">
      <%= render 'company_menu' %>
    </div>
    <div class="col-md-9">
      <div class="panel panel-default">
        <div class="panel-heading">Photos</div>
        <div class="panel-body">
          <div class="container">
            <div class="row">
              <div class="col-md-offset-3 col-md-6">
                Photos upload
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/companies/update.html.erb
<h1>Company#update</h1>
<p>Find me in app/views/company/update.html.erb</p>

app/views/dashboards/index.html.erb
<div class="container content">
  <div class="row">
    <div class="col-md-3">
      <section id="sidebar">
        <nav>
          <center><%= image_tag avatar_url(current_user), class: "img-circle avatar-large" %></center>
          <br>
          <center class="small"><%= current_user.first_name %> <%= current_user.last_name %></center>

          <br><br>
          <a class="active"><i class="far fa-building"></i>&emsp;Companies</a>
          <a href="#"><i class="fas fa-envelope"></i>&emsp;Messages</a>
          <a href="/edit"><i class="fas fa-sliders-h"></i>&emsp;Account settings</a>
          <a href="/edit"><i class="fas fa-key"></i>&emsp;Change password</a>
          <a href="/logout" data-method="delete" rel="nofollow"><i class="fas fa-sign-out-alt"></i>&emsp;Sign out</a>
        </nav>
      </section>  
    </div>
    <div class="col-md-9">
      <h3><strong>Companies</strong></h3>
      <br>
      <div class="panel panel-default">
        <div class="media-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Amount</th>
                <th>Financing Type</th>
                <th>Funded</th>
                <th colspan="3"></th>
              </tr>
            </thead>
            <tbody>
              <% @companies.each do |company| %>
                <tr>
                  <td><%= link_to company.company_name, company %></td>
                  <td><%= company.amount %></td>
                  <td><%= company.financing_type %></td>
                  <td colspan="3"></td>
                </tr>
              <% end %>
            </tbody>
          </table>  
        </div>
      </div>
    </div>
  </div>   
</div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finance</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="https://use.typekit.net/lnl8hjo.css">
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  </head>

  <body>
    <% flash.each do |key, value| %>
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= value %>
        </div>
      <% end %>
    <% end %>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/careers.html.erb
<h1>Pages#careers</h1>
<p>Find me in app/views/pages/careers.html.erb</p>

app/views/pages/client_stories.html.erb
<h1>Pages#client_stories</h1>
<p>Find me in app/views/pages/client_stories.html.erb</p>

app/views/pages/faq.html.erb
<h1>Pages#faq</h1>
<p>Find me in app/views/pages/faq.html.erb</p>

app/views/pages/home.html.erb
<div class="container content">
  <h3>Home</h3>
</div>

app/views/pages/invoice_factoring.html.erb
<h1>Pages#invoice_factoring</h1>
<p>Find me in app/views/pages/invoice_factoring.html.erb</p>

app/views/pages/line_of_credit.html.erb
<h1>Pages#line_of_credit</h1>
<p>Find me in app/views/pages/line_of_credit.html.erb</p>

app/views/pages/partner.html.erb
<h1>Pages#partner</h1>
<p>Find me in app/views/pages/partner.html.erb</p>

app/views/pages/press.html.erb
<h1>Pages#press</h1>
<p>Find me in app/views/pages/press.html.erb</p>

app/views/pages/privacy.html.erb
<h1>Pages#privacy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/pages/support.html.erb
<h1>Pages#support</h1>
<p>Find me in app/views/pages/support.html.erb</p>

app/views/pages/terms.html.erb
<h1>Pages#terms</h1>
<p>Find me in app/views/pages/terms.html.erb</p>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <ul class="navbar-nav navbar-left no-bullet">
      <li><%= link_to "Line of Credit", line_of_credit_path %></li>  
      <li><%= link_to "Invoice Factoring", invoice_factoring_path %></li>
      <li><%= link_to "Partner", partner_path %></li>
      <li><%= link_to "Press", press_path %></li>
      <li><%= link_to "Support", support_path %></li>
    </ul>
    <ul class="navbar-nav navbar-right no-bullet">
      <li><%= link_to 'Terms of Service', terms_path %></li>
      <li><%= link_to 'Privacy', terms_privacy_policy_path %></li> 
      <li>&copy; 2018 Wefactor.com</li> 
    </ul>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<% if (!user_signed_in?) %>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-top">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Wefactor", root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="navbar-top">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Line of Credit", line_of_credit_path %></li>
          <li><%= link_to "Invoice Factoring", invoice_factoring_path %></li>
          <li><%= link_to "About Us", about_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "text-primary" %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>
<% else %>

  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-top">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Wefactor", root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="navbar-top">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
              role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.first_name %> <%= current_user.last_name %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Dashboard", dashboard_path %>
              </li>
              <li><%= link_to "Account Settings", edit_user_registration_path %></li>
                <li><%= link_to 'Change password', edit_user_registration_path %></li>
                <li><%= link_to('Sign out', destroy_user_session_path, method: :delete) %></li>
              </ul>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav> 

<% end %>